### ISSUE TITLE
advice on dealing with glibc build dependencies on alpine?

### ISSUE THREAD

**Issue by cboettig** [artemklevtsov/r-alpine#1]
Hey @artemklevtsov , thanks again for getting in touch about your r-alpine images, sorry it appears now isn't the time to move include them on rocker-org.  I've been playing around with them a bit and getting used to alpine; which has largely gone smoothly but I'm getting hung up by it's uclibc-based toolchain.  I installed https://github.com/sgerrand/alpine-pkg-glibc 's glibc apk, but trying to build RStudio from source I seem to be missing `execinfo.h`, which is seems to be specific to glibc's `backtrace()`.  Any suggestions? Here's my current alpine Dockerfile for an RStudio build: https://github.com/cboettig/r-alpine/blob/master/rstudio/Dockerfile

Thanks for your thoughts.

**Comment by artemklevtsov** [comment]
The `libexecinfo-dev` package contains `execinfo.h`. I think you should try to install it before build.

**Comment by cboettig** [comment]
Thanks that sounds promising, but I was not able to find `libexecinfo-dev` in the apk repos on the alpine images:

```
apk update
apk search libexecinfo-dev
```

comes up blank, as do any variants of `execinfo` or `backtrace`.  Maybe I'm supposed to add some other repo to apk first? Still learning my way around the alpine package manager...

**Comment by cboettig** [comment]
Ah, sorry, looks like I needed
```
apk add libexecinfo-dev --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main --allow-untrusted
```

thanks for the help!

**Comment by artemklevtsov** [comment]
I use `alpine:edge` base image for the tests.

**Comment by cboettig** [comment]
Thanks!  That does solve my `execinfo.h` header issue; though for some reason I'm still failing to build the RStudio sources on alpine-r, getting what look to be many C++ coding errors like:

```
/rstudio-0.99.903/src/cpp/core/include/core/r_util/RVersionInfo.hpp:113:36: error: expected primary-expression before ')' token
    os << ver.major() << "." << ver.minor() << "." << ver.patch();
```

but must be related to something I'm doing on alpine as it installs fine on Debian.  Ever tried building RStudio on alpine? Any thoughts on how to debug this?

Here's [my Dockerfile](https://github.com/cboettig/r-alpine/blob/master/rstudio/Dockerfile) and the [full build log](https://circleci.com/api/v1.1/project/github/cboettig/r-alpine/2/output/9/0?file=true).

**Comment by artemklevtsov** [comment]
It is a complicated program to compile. I have some troubles on my Arch Linux. I didn't try build it on the Alpine.
I think we should try a various `CFLAGS` first.
