### ISSUE TITLE
Parametrized minimal image for running predefined libs

### ISSUE THREAD

**Issue by lahma** [artemklevtsov/r-alpine#3]
Thank you for your effort on creating a small base image, it's much appreciated!

I've examined the resulting image and I have a question/suggestion. My use case is to have Rserve running and taking requests for calculations. So no user interaction or later package installs after initial installation.

Would it be possible to parameterize this even further to:

### Allow installing of ARG based libs (I want to have Rserve and couple supporting libs)

Something like 
```
RUN R -e "install.packages( \
        pkgs=c('Rserve', 'some-other-libs'), \
        repos='https://mran.revolutionanalytics.com/snapshot/2016-11-01', \
        clean=TRUE,\
        INSTALL_opts=c('--no-docs', '--no-data', '--no-help', '--no-demo', '--without-keep.source'));" \
```
As you can see in my example I would also prefer paramerized default repo. MRAN gives repeatable builds with snaphots of libs.

### Remove everything that is not needed after initial package installation/compilation

Uninstall all apk artifacts that are no longer required when no further installations will be done after image building (g++ etc)

For my scenario image libs (tiff etc)  are redundant too but I guess many would require them.

Would this be feasible at all or should I (can I?) for another version with attribution for this version for supporting "headless running of predefined fronzen setup".

**Comment by artemklevtsov** [comment]
I think you should do something like this:

```
FROM artemklevtsov/r-alpine:latest
ENV SYS_DEPS lib1 lib2
ENV R_DEPS pkg1 pkg2

RUN apk --no-cache add ${SYS_DEPS}
RUN Rscript -e 'install.packages(commandArgs(TRUE))' ${R_DEPS}
```

**Comment by lahma** [comment]
This would require these ENVs to be supported by artemklevtsov/r-alpine Dockerfile? Otherwise base image would commit layer and disk space would be lost after that base layer is committed. What's I'm trying to achieve here is to get smallest possible base image before applying my own changes.

**Comment by artemklevtsov** [comment]
Can you provide a PR?

**Comment by lahma** [comment]
Sure, I'll look into this this weekend. Thanks for the quick replies!

**Comment by lahma** [comment]
I've investigated the matter some more and it seems that using APK package might be easier solution when it comes to making later cleanups and reducing the image size. Dockerfile format is quite hard for this kind of customization. 

So closing for now.
